version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      args:
        - CONTAINER_USER=vscode
    tty: true
    volumes:
      - ../:/workspace
    environment:
      - CONTAINER_USER=vscode
